sudo: required
dist: trusty

before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
- sudo apt-get update -qq

install:

- sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
- sudo apt-get install qt5-default qttools5-dev-tools

script:
- source /opt/qt55/bin/qt55-env.sh
- cd src
- /opt/qt55/bin/qmake -project
- /opt/qt55/bin/qmake
- make