######################################################################
# Automatically generated by qmake (2.01a) Mo. Jun 24 11:34:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT +=gui
QT +=widgets

# Input
HEADERS += spiel.h spiel.cpp
SOURCES += main.cpp spiel.cpp
